- name: Setup RasberryPi
  hosts: host
  become: true

  tasks:
    - name: Install Common Package
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - zsh
        - git
        - vim

    - name: Create Timezone file.
      copy:
        content="Asia/Tokyo"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644

    - name: update timezone
      shell: dpkg-reconfigure --frontend noninteractive tzdata

    - name: Add User
      user:
        name: servak
        shell: /usr/bin/zsh

    - name: Set authorized key took from url
      authorized_key:
        user: servak
        state: present
        key: https://github.com/servak.keys

    - name: Install Build Package
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - build-essential
        - automake
        - pkg-config
        - pcscd
        - libpcsclite-dev
        - pcsc-tools
        - unzip

    - name: set firmware
      stat: path=/usr/local/bin/b25
      register: f

    - shell: |
        curl -sL https://github.com/stz2012/libarib25/archive/09770e3.tar.gz | sudo tar zxv
        cd libarib25-09770e334837f6c67268c41c1c15784373d35e5b
        sudo chown -R $(whoami) .
        make
        sudo make install
      args:
        chdir: /usr/local/src
      when: not f.stat.exists


    - name: add recdvb command
      stat: path=/usr/local/bin/recdvb
      register: f

    - shell: |
        curl -sL http://www13.plala.or.jp/sat/recdvb/recdvb-1.3.1.tgz | sudo tar zxv
        cd recdvb-1.3.1
        sudo chown -R $(whoami) .
        ./autogen.sh
        ./configure --enable-b25
        make
        sudo make install
      args:
        chdir: /usr/local/src
      when: not f.stat.exists
